CREATE TABLE IF NOT EXISTS history (
    message_id INTEGER(64) PRIMARY KEY NOT NULL,
    user_id INTEGER(64) NOT NULL,
    date INTEGER(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS last_id (
    id INTEGER PRIMARY KEY NOT NULL,
    message_id INTEGER(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER(64) PRIMARY KEY NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(20) NOT NULL
);
